max_number_of_devices = 100
states = ["Excellent", "Good", "Warning", "Faulty", "Killed", "Unknow"]
delay = 20

[missions]
    orbit_one.name = "OrbitOne"
    orbit_one.abbreviation = "ORBONE"
    orbit_one.devices = ["satellite", "spacecraft", "spacesuit"]

    colony_moon.name = "ColonyMoon"
    colony_moon.abbreviation = "CLNM"
    colony_moon.devices = ["satellite", "spacecraft", "spacesuit", "spacecars"]

    vac_mars.name = "VacMars"
    vac_mars.abbreviation = "VCMS"
    vac_mars.devices = ["satellite", "spacecraft", "spacesuit", "spacecars"]

    galaxy_two.name = "GalaxyTwo"
    galaxy_two.abbreviation = "GXTO"
    galaxy_two.devices = ["satellite", "spacecraft", "spacesuit", "scientific_equipment"]